### ISSUE TITLE
Extra comma

### ISSUE THREAD

**Issue by amt925** [kwoodfriend/simple-ajax-form#1]
There is an extra comma here: https://github.com/kwoodfriend/simple-ajax-form/blob/master/SimpleAjaxForm.js#L32

**Comment by kwoodfriend** [comment]
FYI, extra commas are only an issue for older browsers. Maybe <= IE 7? Don't remember, but's it's not an issue these days. It's even in ES5. I updated it, so it would stop annoying you, but you might want to ignore it in jslint/hint.
